import { NextResponse } from 'next/server';

export async function POST(request: Request) {
  const { prompt } = await request.json();
  
  // Here we would call the AI provider based on the active model configuration
  // For now, returning a mock response to satisfy the interface.
  
  return NextResponse.json({ 
    text: JSON.stringify({
      narrative: "This is a mock narrative generated by the backend.",
      options: [
        { id: "opt1", title: "Concept 1", angle: "Angle 1", hook: "Hook 1", format: "POV", whyItWorks: "Works well." },
        { id: "opt2", title: "Concept 2", angle: "Angle 2", hook: "Hook 2", format: "Storytime", whyItWorks: "Works well." },
        { id: "opt3", title: "Concept 3", angle: "Angle 3", hook: "Hook 3", format: "Reaction", whyItWorks: "Works well." }
      ]
    })
  });
}
